ggp:
	g++ source/myutils.cpp source/Avatar.cpp source/Cell.cpp source/Region.cpp source/Server.cpp source/simcosmmus.cpp -lSDL -lSDL_ttf -o simcosmmus -g

clean:
	rm simcosmmus && clear && echo "Clear"
